name: CMake

on:
  push:
    branches: [ master ]
    paths: [ CMakeLists.txt, 'src/**', 'd2mapapi/**', 'common/**', 'tools/**', 'json/**', 'inih/**' ]
  pull_request:
    branches: [ master ]
    paths: [ CMakeLists.txt, 'src/**', 'd2mapapi/**', 'common/**', 'tools/**', 'json/**', 'inih/**' ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup Environment
      shell: pwsh
      run: echo "C:\msys64\mingw32\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: CMake Configure
      run: cmake -B ${{github.workspace}}/mingw32_build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_STATIC_CRT=ON

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/mingw32_build --target snapshot-pack

    - uses: actions/upload-artifact@v2
      with: 
        name: D2RMH-snapshot
        path: |
          ${{github.workspace}}/mingw32_build/bin/D2RMH-snapshot.zip
        retention-days: 7