name: CMake

on:
  push:
    branches: [ master ]
    paths: [ ".github/workflows/build.yml", CMakeLists.txt, 'src/**', 'd2mapapi/**', 'common/**', 'tools/**', 'json/**', 'inih/**' ]
  pull_request:
    branches: [ master ]
    paths: [ ".github/workflows/build.yml", CMakeLists.txt, 'src/**', 'd2mapapi/**', 'common/**', 'tools/**', 'json/**', 'inih/**' ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - generator: MinGW Makefiles
            ident: mingw32
          - generator: Visual Studio 16 2019
            ident: vc2019
            extra_flags: -A Win32

    steps:
      - name: Setup Environment
        shell: pwsh
        run: echo "C:\msys64\mingw32\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: CMake Configure
        run: cmake -B "${{github.workspace}}/${{matrix.ident}}_build" -G "${{matrix.generator}}" ${{matrix.extra_flags}} -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}" -DUSE_STATIC_CRT=ON

      - name: Build
        # Build your program with the given configuration
        run: cmake --build "${{github.workspace}}/${{matrix.ident}}_build" --config "${{env.BUILD_TYPE}}" --target snapshot-pack -j

      - uses: actions/upload-artifact@v2
        with:
          name: D2RMH-snapshot-${{matrix.ident}}
          path: |
            ${{github.workspace}}/${{matrix.ident}}_build/bin/D2RMH-snapshot.zip
          retention-days: 7